exclude: ^(data/).*

repos:
  - repo: https://github.com/doublify/pre-commit-rust
    rev: v1.0
    hooks:
      - id: fmt
      - id: cargo-check
      - id: clippy
        args: [ "--", "-D", "warnings", "-A", "clippy::too-many-arguments" ]

  - repo: https://github.com/pre-commit/pre-commit-hooks
    rev: v4.4.0
    hooks:
      - id: trailing-whitespace
        exclude_types: [ markdown ]
      - id: end-of-file-fixer
      - id: check-yaml
      - id: check-added-large-files
